name: Deploy Angular to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
      
      # Limpiar dependencias y lock
      - name: Clean node_modules and package-lock
        run: |
          rm -rf node_modules package-lock.json

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Build Angular
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
