name: Deploy Angular to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 17.3.6

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # Build Angular
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Deploy Firebase Hosting
      - name: Deploy to Firebase
        run: npx firebase deploy --only hosting --token "$FIREBASE_TOKEN"
